# Write your MySQL query statement below
WITH t AS(
    SELECT
        REGEXP_SUBSTR(tweet, '#\\w+') AS HASHTAG
    FROM Tweets
)
SELECT HASHTAG, COUNT(HASHTAG) AS HASHTAG_COUNT 
FROM t
GROUP BY HASHTAG
ORDER BY COUNT(HASHTAG) DESC, HASHTAG DESC
LIMIT 3;